hmpps-auth:
  url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"

openfoodfacts:
  api:
    url: "https://world.openfoodfacts.org"
openproductsfacts:
  api:
    url: "https://world.openproductsfacts.org"