generic-service:
  nameOverride: hmpps-digital-canteen-api
  productId: "DPS128" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-digital-canteen-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-digital-canteen-api-cert

  # Environment variables to load into the deployment
  env:
    - name: SERVER_PORT
      value: "8080"

    - name: APPLICATIONINSIGHTS_CONFIGURATION_FILE
      value: "applicationinsights.json"

    - name: DB_HOST
      valueFrom:
          secretKeyRef:
            name: rds-postgresql-instance-output
            key: rds_instance_address

    - name: DB_NAME
      valueFrom:
          secretKeyRef:
            name: rds-postgresql-instance-output
            key: database_name

    - name: DB_USER
      valueFrom:
          secretKeyRef:
            name: rds-postgresql-instance-output
            key: database_username

    - name: DB_PASSWORD
      valueFrom:
          secretKeyRef:
            name: rds-postgresql-instance-output
            key: database_password


  namespace_secrets:
    hmpps-digital-canteen-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-digital-canteen-api
