---
# Per environment values which override defaults in hmpps-digital-canteen-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: digital-canteen-dev.prison.service.justice.gov.uk

  env:
      - name: APPLICATIONINSIGHTS_CONFIGURATION_FILE
        value: "applicationinsights.dev.json"

      - name: AUTH_URL
        value: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"

      - name: SPRINGDOC_API-DOCS_ENABLED
        value: "true"

      - name: SPRINGDOC_SWAGGER-UI_ENABLED
        value: "true"

      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: rds-postgresql-instance-output
            key: rds_instance_address

      - name: DB_NAME
        valueFrom:
          secretKeyRef:
            name: rds-postgresql-instance-output
            key: database_name

      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: rds-postgresql-instance-output
            key: database_username

      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: rds-postgresql-instance-output
            key: database_password


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: n/a
